language: r
warnings_are_errors: false
sudo: required
cache: packages
r_packages:
 - devtools
r_github_packages:
 - hrbrmstr/albersusa

matrix:
    #allow_failures:
    #    -os: osx
    include:
        - os: linux
          r: release
          dist: bionic
          env: R_CODECOV=true
        - os: linux
          r: devel
          dist: bionic

# before_install:
#     - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
#     - sudo apt-get --yes --force-yes update -qq
#     - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - netcdf-bin

notifications:
  email:
    on_success: change
    on_failure: change


